server: 
  port: 3344

spring:
  application:
    name: configServer3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lichen1993/springcloud-config.git
